name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [g++, clang++]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt update
            sudo apt install -y cmake clang cppcheck clang-tidy cmake build-essential
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew update
            brew install cmake ${{ matrix.compiler }} cppcheck clang-tidy cmake
          fi

      - name: Configure and build project with CMake
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
          cmake --build .
